name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        node-version-file: '.nvmrc'

    - name: Install dependencies
      run: npm ci
      env:
        NODE_ENV: test

    - name: Run Unit Tests
      run: npm run test
      env:
        NODE_ENV: test

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      env:
        NODE_ENV: test

    - name: Run E2E Tests
      run: npm run test:e2e
      env:
        NODE_ENV: test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        node-version-file: '.nvmrc'

    - name: Install dependencies
      run: npm ci
      env:
        NODE_ENV: production

    - name: Build Project
      run: npm run build
      env:
        NODE_ENV: production 